trigger:
  - master

  

# this section would run it in azure devops 
# pool:
#   vmImage: 'ubuntu-latest'
# strategy:
#   matrix:
#     Python27:
#       python.version: '2.7'
#     Python37:
#       python.version: '3.7'
# steps:
    
#   - script: |
#       conda env create --file environment.yml
#       /usr/share/miniconda/envs/napari/bin/python -m pip install pytest pytest-azurepipelines
#       /usr/share/miniconda/envs/napari/bin/python -m pytest
#     displayName: 'Setup conda/install dependencies, run tests'


pool:
  name: ctomerodev
steps:
  - script: |
      touch OMERO_Properties.py
      echo "USERNAME='$(TEST_OMERO_USER)'" >> OMERO_Properties.py
      echo "PASSWORD = '$(TEST_OMERO_PASS)'" >> OMERO_Properties.py
      echo "HOST = '$(TEST_OMERO_HOST)'" >> OMERO_Properties.py
      echo "PORT = $(TEST_PORT)" >> OMERO_Properties.py
      
    displayName: 'Create file with variables/secrets'
    env:
      TEST_OMERO_PASS: $(TEST_OMERO_PASS) 

  - script: |
      docker build -t napari_omero:v1 .
    displayName: 'Build docker container'

  - script: |
      docker run --rm napari_omero:v1
    displayName: 'Run tests on container'