name: napari
channels:
  - anaconda
  - ome
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - asciitree=0.3.3
  - attrs=19.3.0
  - babel=2.8.0
  - backcall=0.1.0
  - blas=1.0
  - bokeh=2.0.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - cloudpickle=1.3.0
  - cryptography=2.8
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.12.0
  - dask-core=2.12.0
  - dbus=1.13.6
  - decorator=4.4.2
  - distributed=2.12.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.6
  - fasteners=0.14.1
  - fontconfig=2.13.1
  - freetype=2.9.1
  - freetype-py=2.1.0.post1
  - fsspec=0.6.2
  - future=0.18.2
  - gettext=0.19.8.1
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - heapdict=1.0.1
  - icu=64.2
  - idna=2.9
  - imageio=2.8.0
  - imagesize=1.2.0
  - importlib-metadata=1.5.0
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - jupyter_client=5.3.4
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libclang=9.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - locket=0.2.0
  - markupsafe=1.1.1
  - matplotlib-base=3.2.0
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - monotonic=1.5
  - more-itertools=8.2.0
  - msgpack-python=1.0.0
  - napari=0.2.12
  - ncurses=6.2
  - networkx=2.4
  - nspr=4.25
  - nss=3.47
  - numcodecs=0.6.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - omero-py=5.6.0
  - openssl=1.1.1e
  - packaging=20.1
  - pandas=1.0.2
  - parso=0.6.2
  - partd=1.1.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pluggy=0.13.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - psutil=5.7.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.1
  - pycparser=2.20
  - pygments=2.6.1
  - pyopengl=3.1.5
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyyaml=5.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.7.1
  - qtpy=1.9.0
  - readline=7.0
  - requests=2.23.0
  - scikit-image=0.16.2
  - scipy=1.4.1
  - setuptools=46.0.0
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.1.0
  - sphinx=2.4.4
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - tblib=1.6.0
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - vispy=0.6.4
  - wcwidth=0.1.8
  - wheel=0.34.2
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - yaml=0.2.2
  - zarr=2.4.0
  - zeroc-ice36-python=3.6.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pyside2==5.14.1
    - shiboken2==5.14.1

